### ISSUE TITLE
Repository review

### ISSUE THREAD

**Issue by joshmoore** [German-BioImaging/webtagging#76]
cc: @will-moore @jburel @Tom-TBT

* [ ] consider renaming to omero-webtagging
* [ ] update the URL on the landing page (no help.o.org links)
* [ ] ...

**Comment by Tom-TBT** [comment]
Any recommendation to split it in two? `omero-autotag` and `omero-tagsearch`

I found this
https://docs.github.com/en/get-started/using-git/splitting-a-subfolder-out-into-a-new-repository

Better:
make two new one ?
OR 
one new (`omero-autotag` ) and this one becomes `omero-tagsearch`?

**Comment by joshmoore** [comment]
Good question.

Pros:
 - less confusion
 - easier to release separate versions

Cons:
 - makes the history trickier
 - have to decide which (if either) get the original repo (issues, etc.)

**Comment by Tom-TBT** [comment]
Did a split, this is the new repo:
https://github.com/German-BioImaging/omero-autotag

Need to update the README with the README of the original repo, but the history looks to be still here :)

Issues, I can move them between repo apparently

**Comment by Tom-TBT** [comment]
i'm seeing that:
![image](https://github.com/German-BioImaging/webtagging/assets/10853316/787aa94b-8827-4bad-b572-4f479a62c6a4)

better make a second splitted repo then, and archive OMERO.webtagging in my opinion

**Comment by dpwrussell** [comment]
I'm not certain what happens to redirects if you archive a repository.
Hopefully that remains intact so anyone following a link to
https://github.com/MicronOxford/webtagging would not end up with a 404.

Thanks,

Douglas

**Comment by joshmoore** [comment]
> The archiving should just move the repo to a read-only state:

Archived redirects definitely persist (as long as no one re-creates the repository at the redirect location...)

**Comment by Tom-TBT** [comment]
It should now be ready for archiving. I'll do that at the end of the week if nothing else comes up.

**Comment by Tom-TBT** [comment]
No recent comment about archiving this repo
-> closing this issue and archiving the repo
